### ISSUE TITLE
standard_init_linux.go:207: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by SoldierCorp** [chemidy/smallest-secured-golang-docker-image#3]
Hi,

Thank you for upload that example.

When I execute the command `docker run my-project` the following error appears

`standard_init_linux.go:207: exec user process caused "no such file or directory"`

Do you know why?

**Comment by chemidy** [comment]
Hi,

Did you run make build command before?

**Comment by SoldierCorp** [comment]
In this Gist I have the Dockerfile and the commands I am executing https://gist.github.com/SoldierCorp/98f04d026677afcad7cb8b14762eba2a

Can you please take a look there?

Thank you!

**Comment by chemidy** [comment]
Is it ok with my comment on gist ?

**Comment by SoldierCorp** [comment]
Hi!

To fix that issue, yes but two more appeared. I left a comment regarding them in the Gist. Is about a .env file I am using and some permission with the port 80.

Thanks!

**Comment by SoldierCorp** [comment]
Fixed, thank you!!
