### ISSUE TITLE
Reuse host build cache in first build stage

### ISSUE THREAD

**Issue by andig** [chemidy/smallest-secured-golang-docker-image#6]
Running go get/ go mod inside the builder does not create a layer that is persistent. Running build will re-trigger dependencies download every time. At least for local builds it would be great if the host's build cache could be reused (or the builder cache be persisted). I could not find any solution to do this for go build.

**Comment by chemidy** [comment]
I just updated the repo with a new go_module version with cache layer.

Try it please 👍

**Comment by andig** [comment]
Works like a charm- thank you so much!
