### ISSUE TITLE
Distroless?

### ISSUE THREAD

**Issue by StevenACoffman** [chemidy/smallest-secured-golang-docker-image#8]
I love this example, but in your article you mention distroless for the final base image, which I think might simplify things a bit. Do you have a working example of using distroless?

**Comment by chemidy** [comment]
Thks for your mention about distoless, now you can find a go_module_distroless example.

I'm using a nonroot base distroless, so we do not need to add a unprivileged user :)

**Comment by StevenACoffman** [comment]
In reading through the [documentation for distroless] (https://github.com/GoogleContainerTools/distroless/tree/master/base) for `gcr.io/distroless/base` and `gcr.io/distroless/static`:

This image contains a minimal Linux, glibc-based system. It is intended for use directly by "mostly-statically compiled" languages like Go, Rust or D.

Statically compiled applications (Go) that do not require libc can use the `gcr.io/distroless/static` image, which contains:

* ca-certificates
* A /etc/passwd entry for a root user
* A /tmp directory
* tzdata

Most other applications (and Go apps that require libc/cgo) should start with `gcr.io/distroless/base`, which contains all
of the packages in `gcr.io/distroless/static`, and 

* glibc
* libssl
* openssl

**Comment by chemidy** [comment]
By the way there are [differents tags for base images ](https://console.cloud.google.com/gcr/images/distroless/GLOBAL/base?gcrImageListsize=10)not always mentioned in documentation :
- latest
- debug
- nonroot
- debug-nonroot

<img width="1160" alt="Screenshot 2020-01-11 at 09 47 30" src="https://user-images.githubusercontent.com/3128770/72201790-d941f900-3457-11ea-8a38-7b3e4c857f59.png">

You can find all distroless images  [here](https://console.cloud.google.com/gcr/images/distroless) : 
<img width="1161" alt="Screenshot 2020-01-11 at 09 48 36" src="https://user-images.githubusercontent.com/3128770/72201806-07273d80-3458-11ea-93bc-80c8dba01539.png">

**Comment by StevenACoffman** [comment]
Right, so I think if you are static compiling using alpine (musl) it doesn't make sense to use base (you should use static). However, if you are not static compiling your go binary, then you should use a debian builder to use the distroless base.

**Comment by chemidy** [comment]
ok i changed example to use static

**Comment by StevenACoffman** [comment]
I was working on it at the same time! I made a PR with a few other changes, and separated static vs base for distroless.
